Flow Controller:
  name: MiNiFi Flow
Processors:
    # - name: GetFile
    #   class: org.apache.nifi.processors.standard.GetFile
    #   max concurrent tasks: 1
    #   scheduling strategy: TIMER_DRIVEN
    #   scheduling period: 1 sec
    #   penalization period: 30 sec
    #   yield period: 1 sec
    #   run duration nanos: 0
    #   auto-terminated relationships list:
    #   Properties:
    #       Input Directory: /tmp/getfile
    #       Keep Source File: false
    #       File Filter: ".*"
    - name: ListenHTTP
      class: org.apache.nifi.processors.standard.ListenHTTP
      max concurrent tasks: 16
      scheduling strategy: TIMER_DRIVEN
      scheduling period: 1 sec
      penalization period: 30 sec
      yield period: 1 sec
      run duration nanos: 0
      auto-terminated relationships list:
      Properties:
          Listening Port: 8888
          Authorized DN Pattern: /C=AU/ST=Some-State/O=Internet Widgits Pty Ltd/CN=localhost|/C=US/ST=Maryland/O=Internet Widgits Pty Ltd/CN=localhost
          SSL Certificate: /tmp/certs/minifi.pem
          SSL Certificate Authority: /tmp/certs/minifi.crt
          SSL Verify Peer: yes
          SSL Minimum Version: TLS1.2
          HTTP Headers to receive as Attributes (Regex): X-Test2.*
    - name: LogAttribute
      class: org.apache.nifi.processors.standard.LogAttribute
      max concurrent tasks: 1
      scheduling strategy: EVENT_DRIVEN
      scheduling period: 1 sec
      penalization period: 30 sec
      yield period: 1 sec
      run duration nanos: 0
      auto-terminated relationships list:
    - name: PutFile
      class: org.apache.nifi.processors.standard.PutFile
      max concurrent tasks: 1
      scheduling strategy: EVENT_DRIVEN
      scheduling period: 1 sec
      penalization period: 30 sec
      yield period: 1 sec
      run duration nanos: 0
      auto-terminated relationships list: ["success", "failure"]
      Properties:
          Output Directory: /tmp/putfile
Connections:
    # - name: TransferFiles
    #   source name: GetFile
    #   source relationship name: success
    #   destination name: PutFile
    #   max work queue size: 0
    #   max work queue data size: 1 MB
    #   flowfile expiration: 60 sec
    - name: TransferHttpToLogAttribute
      source name: ListenHTTP
      source relationship name: success
      destination name: LogAttribute
      max work queue size: 0
      max work queue data size: 1 MB
      flowfile expiration: 60 sec
    - name: LogAttributeToPutFile
      source name: LogAttribute
      source relationship name: success
      destination name: PutFile
      max work queue size: 0
      max work queue data size: 1 MB
      flowfile expiration: 60 sec
Remote Processing Groups: []
